[package]
name = "metar_alert"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
reqwest = { version = "0.12.12", features = ["json"]}
tokio = { version = "1.43.0", features = ["full"] }
tokio-macros = "2.5.0"
